### ISSUE TITLE
MP4 doesn't work in Firefox, IE 8

### ISSUE THREAD

**Issue by rbruch** [collective/collective.mediaelementjs#4]
MP4 format doesn't work in Firefox & IE 8 due to path problem for flashmediaelement.swf. Trying to view gives generated code in <embed> tag, src="flashmediaelement.swf" but that results in NotFound error.

Versions: Fx 22, IE 8, Plone 4.2.6, c.mediaelementjs 0.4.1

**Comment by agitator** [comment]
please reopen if still an issue
